export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const MY_REVIEWS_REQUEST = "NEW_REVIEW_REQUEST";
export const MY_REVIEWS_SUCCESS = "NEW_REVIEW_SUCCESS";
export const MY_REVIEWS_FAIL = "NEW_REVIEW_FAIL";

export const MY_SINGLE_REVIEW_REQUEST = "MY_SINGLE_REVIEW_REQUEST";
export const MY_SINGLE_REVIEW_SUCCESS = "MY_SINGLE_REVIEW_SUCCESS";
export const MY_SINGLE_REVIEW_FAIL = "MY_SINGLE_REVIEW_FAIL";

export const MY_REVIEW_UPDATE_REQUEST = "MY_REVIEW_UPDATE_REQUEST";
export const MY_REVIEW_UPDATE_SUCCESS = "MY_REVIEW_UPDATE_SUCCESS";
export const MY_REVIEW_UPDATE_FAIL = "MY_REVIEW_UPDATE_FAIL";
export const MY_REVIEW_UPDATE_RESET = "MY_REVIEW_UPDATE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
